// ============ GRAHAS (PLANETS) DATA ============
const GRAHAS = [
  {
    name: "Surya",
    en: "Sun",
    sym: "☉",
    color: "#e8a33a",
    ruler: "Leo",
    exalt: "Aries 10°",
    debl: "Libra 10°",
    mt: "Leo 0–20°",
    friends: ["Moon", "Mars", "Jupiter"],
    enemies: ["Saturn", "Venus"],
    neutral: ["Mercury"],
    nature: "Krura (Cruel)",
    gender: "Male",
    caste: "Kshatriya",
    rep: [
      "Soul (Atma)",
      "Father",
      "Authority & Power",
      "Vitality & Health",
      "Ego & Self-esteem",
      "Government & Kingship",
      "Right Eye",
      "Daytime",
    ],
    body: ["Heart", "Eyes", "Brain", "Bones", "Stomach"],
    day: "Sunday",
    dir: "East",
  },
  {
    name: "Chandra",
    en: "Moon",
    sym: "☽",
    color: "#c8c8e8",
    ruler: "Cancer",
    exalt: "Taurus 3°",
    debl: "Scorpio 3°",
    mt: "Taurus 3–30°",
    friends: ["Sun", "Mercury"],
    enemies: [],
    neutral: ["Mars", "Jupiter", "Venus", "Saturn"],
    nature: "Saumya (Gentle)",
    gender: "Female",
    caste: "Vaishya",
    rep: [
      "Mind (Manas)",
      "Mother",
      "Emotions & Feelings",
      "Intuition",
      "Public & Masses",
      "Left Eye",
      "Water & Liquids",
      "Females in General",
    ],
    body: ["Mind", "Blood", "Breast", "Lungs"],
    day: "Monday",
    dir: "Northwest",
  },
  {
    name: "Mangala",
    en: "Mars",
    sym: "♂",
    color: "#e85d3a",
    ruler: "Aries & Scorpio",
    exalt: "Capricorn 28°",
    debl: "Cancer 28°",
    mt: "Aries 0–12°",
    friends: ["Sun", "Moon", "Jupiter"],
    enemies: ["Mercury", "Ketu"],
    neutral: ["Venus", "Saturn", "Rahu"],
    nature: "Krura (Cruel)",
    gender: "Male",
    caste: "Kshatriya",
    rep: [
      "Energy & Courage",
      "Action & Initiative",
      "Brothers & Siblings",
      "Weapons & Military",
      "Accidents & Injuries",
      "Land & Property",
      "Blood",
      "Muscular System",
    ],
    body: ["Blood", "Bone Marrow", "Muscles", "Bile"],
    day: "Tuesday",
    dir: "South",
  },
  {
    name: "Budha",
    en: "Mercury",
    sym: "☿",
    color: "#6ac47a",
    ruler: "Gemini & Virgo",
    exalt: "Virgo 15°",
    debl: "Pisces 15°",
    mt: "Virgo 15–20°",
    friends: ["Sun", "Venus"],
    enemies: ["Moon"],
    neutral: ["Mars", "Jupiter", "Saturn", "Rahu", "Ketu"],
    nature: "Saumya (Gentle)",
    gender: "Neuter",
    caste: "Vaishya",
    rep: [
      "Intellect & Speech",
      "Commerce & Trade",
      "Writing & Communication",
      "Education & Learning",
      "Mathematics",
      "Astrology",
      "Skin",
      "Nervous System",
    ],
    body: ["Nervous System", "Skin", "Lungs", "Intestines"],
    day: "Wednesday",
    dir: "North",
  },
  {
    name: "Guru",
    en: "Jupiter",
    sym: "♃",
    color: "#d4a040",
    ruler: "Sagittarius & Pisces",
    exalt: "Cancer 5°",
    debl: "Capricorn 5°",
    mt: "Sagittarius 0–10°",
    friends: ["Sun", "Moon", "Mars"],
    enemies: ["Mercury", "Venus"],
    neutral: ["Saturn", "Rahu", "Ketu"],
    nature: "Saumya (Gentle)",
    gender: "Male",
    caste: "Brahmin",
    rep: [
      "Wisdom & Knowledge",
      "Children & Progeny",
      "Wealth & Fortune",
      "Dharma & Righteousness",
      "Spirituality",
      "Teachers & Gurus",
      "Justice",
      "Expansion",
    ],
    body: ["Liver", "Fat", "Kidneys", "Thighs"],
    day: "Thursday",
    dir: "Northeast",
  },
  {
    name: "Shukra",
    en: "Venus",
    sym: "♀",
    color: "#c491d1",
    ruler: "Taurus & Libra",
    exalt: "Pisces 27°",
    debl: "Virgo 27°",
    mt: "Libra 0–20°",
    friends: ["Mercury", "Saturn"],
    enemies: ["Sun", "Moon"],
    neutral: ["Mars", "Jupiter", "Rahu", "Ketu"],
    nature: "Saumya (Gentle)",
    gender: "Female",
    caste: "Vaishya",
    rep: [
      "Love & Relationships",
      "Beauty & Aesthetics",
      "Luxury & Comfort",
      "Arts & Music",
      "Marriage & Partnership",
      "Desire",
      "Pleasure",
      "Material Prosperity",
    ],
    body: ["Reproductive System", "Semen", "Eyes", "Skin"],
    day: "Friday",
    dir: "Southeast",
  },
  {
    name: "Shani",
    en: "Saturn",
    sym: "♄",
    color: "#8b7355",
    ruler: "Capricorn & Aquarius",
    exalt: "Libra 20°",
    debl: "Aries 20°",
    mt: "Capricorn 0–20°",
    friends: ["Mercury", "Venus"],
    enemies: ["Sun", "Moon", "Mars"],
    neutral: ["Jupiter", "Rahu", "Ketu"],
    nature: "Krura (Cruel)",
    gender: "Neuter",
    caste: "Shudra",
    rep: [
      "Time & Karma",
      "Discipline & Limitation",
      "Hard Work & Perseverance",
      "Longevity",
      "Fear & Sorrow",
      "Obstacles",
      "Delayed Results",
      "Servant & Service",
    ],
    body: ["Bones", "Teeth", "Hair", "Nails"],
    day: "Saturday",
    dir: "West",
  },
  {
    name: "Rahu",
    en: "North Node",
    sym: "☊",
    color: "#a55b1f",
    ruler: "N/A (Virgo traditionally)",
    exalt: "Taurus",
    debl: "Scorpio",
    mt: "N/A",
    friends: ["Mercury", "Venus", "Saturn"],
    enemies: ["Sun", "Moon"],
    neutral: ["Mars", "Jupiter", "Ketu"],
    nature: "Krura (Cruel)",
    gender: "Neuter",
    caste: "Chandala",
    rep: [
      "Desires & Obsessions",
      "Illusion & Delusion",
      "Worldly Success",
      "Shadows & Deception",
      "Insatiable Hunger",
      "Innovation & Technology",
      "Foreign Travel",
      "Extremism",
    ],
    body: ["Lymphatic System", "Respiratory System"],
    day: "N/A",
    dir: "N/A",
  },
  {
    name: "Ketu",
    en: "South Node",
    sym: "☋",
    color: "#6b4f3f",
    ruler: "N/A (Pisces traditionally)",
    exalt: "Scorpio",
    debl: "Taurus",
    mt: "N/A",
    friends: ["Mars", "Jupiter"],
    enemies: ["Sun", "Moon"],
    neutral: ["Mercury", "Venus", "Saturn", "Rahu"],
    nature: "Krura (Cruel)",
    gender: "Neuter",
    caste: "Chandala",
    rep: [
      "Spirituality & Detachment",
      "Psychic Abilities",
      "Past Karma",
      "Dissatisfaction",
      "Cuts & Separations",
      "Healing & Wisdom",
      "Hidden Knowledge",
      "Moksha Path",
    ],
    body: ["Lymphatic System", "Hormones"],
    day: "N/A",
    dir: "N/A",
  },
];

// ============ RASHIS (ZODIAC SIGNS) DATA ============
const RASHIS = [
  {
    name: "Mesha",
    en: "Aries",
    symbol: "♈",
    element: "Fire",
    ruler: "Mars",
    exalt: "Sun",
    debl: "Saturn",
    quality: "Cardinal",
    range: "0° – 30°",
    color: "#e8713a",
    desc: "Pioneer, courageous, initiator. Self-driven energy.",
  },
  {
    name: "Vrishabha",
    en: "Taurus",
    symbol: "♉",
    element: "Earth",
    ruler: "Venus",
    exalt: "Moon",
    debl: "Rahu",
    quality: "Fixed",
    range: "30° – 60°",
    color: "#7a9e3a",
    desc: "Stable, sensual, material focus. Enduring strength.",
  },
  {
    name: "Mithuna",
    en: "Gemini",
    symbol: "♊",
    element: "Air",
    ruler: "Mercury",
    exalt: "Rahu",
    debl: "Ketu",
    quality: "Mutable",
    range: "60° – 90°",
    color: "#5a9ed4",
    desc: "Communicative, adaptive, intellectual curiosity.",
  },
  {
    name: "Karka",
    en: "Cancer",
    symbol: "♋",
    element: "Water",
    ruler: "Moon",
    exalt: "Jupiter",
    debl: "Mars",
    quality: "Cardinal",
    range: "90° – 120°",
    color: "#4a6ed4",
    desc: "Emotional, nurturing, protective home focus.",
  },
  {
    name: "Simha",
    en: "Leo",
    symbol: "♌",
    element: "Fire",
    ruler: "Sun",
    exalt: "Mercury",
    debl: "Saturn",
    quality: "Fixed",
    range: "120° – 150°",
    color: "#e8a33a",
    desc: "Royal, creative, expressive leadership.",
  },
  {
    name: "Kanya",
    en: "Virgo",
    symbol: "♍",
    element: "Earth",
    ruler: "Mercury",
    exalt: "Mercury",
    debl: "Venus",
    quality: "Mutable",
    range: "150° – 180°",
    color: "#6ac47a",
    desc: "Analytical, practical, service-oriented refinement.",
  },
  {
    name: "Tula",
    en: "Libra",
    symbol: "♎",
    element: "Air",
    ruler: "Venus",
    exalt: "Saturn",
    debl: "Sun",
    quality: "Cardinal",
    range: "180° – 210°",
    color: "#c491d1",
    desc: "Balanced, artistic, relationship-focused harmony.",
  },
  {
    name: "Vrischika",
    en: "Scorpio",
    symbol: "♏",
    element: "Water",
    ruler: "Mars",
    exalt: "Ketu",
    debl: "Moon",
    quality: "Fixed",
    range: "210° – 240°",
    color: "#a33b2e",
    desc: "Intense, mysterious, transformative depth.",
  },
  {
    name: "Dhanus",
    en: "Sagittarius",
    symbol: "♐",
    element: "Fire",
    ruler: "Jupiter",
    exalt: "N/A",
    debl: "Mercury",
    quality: "Mutable",
    range: "240° – 270°",
    color: "#d4a040",
    desc: "Expansive, philosophical, adventurous truth-seeking.",
  },
  {
    name: "Makara",
    en: "Capricorn",
    symbol: "♑",
    element: "Earth",
    ruler: "Saturn",
    exalt: "Mars",
    debl: "Jupiter",
    quality: "Cardinal",
    range: "270° – 300°",
    color: "#8b7355",
    desc: "Ambitious, disciplined, methodical achievement.",
  },
  {
    name: "Kumbha",
    en: "Aquarius",
    symbol: "♒",
    element: "Air",
    ruler: "Saturn",
    exalt: "Rahu",
    debl: "Sun",
    quality: "Fixed",
    range: "300° – 330°",
    color: "#5a9ed4",
    desc: "Innovative, humanitarian, independent ideals.",
  },
  {
    name: "Meena",
    en: "Pisces",
    symbol: "♓",
    element: "Water",
    ruler: "Jupiter",
    exalt: "Venus",
    debl: "Mercury",
    quality: "Mutable",
    range: "330° – 360°",
    color: "#a569d4",
    desc: "Intuitive, spiritual, compassionate imagination.",
  },
];

// ============ BHAVAS (HOUSES) DATA ============
const BHAVAS = [
  {
    number: 1,
    name: "Lagna/Tanhu",
    en: "Self",
    keywords: "Identity, Appearance, Character",
    significance:
      "The physical body, personality, and overall life direction. This house represents the native and their fundamental nature.",
  },
  {
    number: 2,
    name: "Dhana",
    en: "Wealth",
    keywords: "Finance, Family, Speech",
    significance:
      "Material possessions, wealth, family background, and the quality of speech. Second house indicates accumulated resources.",
  },
  {
    number: 3,
    name: "Sahaja",
    en: "Siblings",
    keywords: "Communication, Courage, Short Travel",
    significance:
      "Brothers and sisters, communication abilities, short journeys, and skills. Ruled by Mercury naturally.",
  },
  {
    number: 4,
    name: "Bandhu",
    en: "Home & Mother",
    keywords: "Property, Vehicles, Mother, Happiness",
    significance:
      "Home, real estate, vehicles, emotional foundation, and mother. Represents inner peace and domestic matters.",
  },
  {
    number: 5,
    name: "Putra",
    en: "Children",
    keywords: "Creativity, Intelligence, Speculation",
    significance:
      "Children, creative expression, intelligence, romance, and games of chance. Leo's natural house.",
  },
  {
    number: 6,
    name: "Ari",
    en: "Enemies & Health",
    keywords: "Illness, Debts, Opposition, Enemies",
    significance:
      "Health issues, debts, enemies, and obstacles. Challenges that build character through struggle.",
  },
  {
    number: 7,
    name: "Yuvati",
    en: "Spouse & Partnerships",
    keywords: "Marriage, Partnerships, Agreements, Trade",
    significance:
      "Marriage partner, business partnerships, and significant relationships. Represents the 'other' in contracts.",
  },
  {
    number: 8,
    name: "Randhra",
    en: "Transformation & Longevity",
    keywords: "Death, Inheritance, Mysteries, Occult",
    significance:
      "Transformation, hidden powers, sudden events, inherited wealth, and deeper mysteries of existence.",
  },
  {
    number: 9,
    name: "Dharma",
    en: "Fortune & Dharma",
    keywords: "Luck, Philosophy, Long Travel, Father",
    significance:
      "Luck, dharma, higher learning, spiritual inclinations, long journeys, and paternal relationships.",
  },
  {
    number: 10,
    name: "Karma",
    en: "Career & Public Image",
    keywords: "Profession, Authority, Reputation, Public Standing",
    significance:
      "Career, public reputation, authority, and life direction. The highest point of achievement in life.",
  },
  {
    number: 11,
    name: "Labha",
    en: "Gains & Friendships",
    keywords: "Friendship, Income, Wishes Fulfilled, Community",
    significance:
      "Financial gains, friendships, fulfillment of desires, and social networks. House of abundance and associations.",
  },
  {
    number: 12,
    name: "Vyaya",
    en: "Losses & Spiritual Liberation",
    keywords: "Expenses, Foreign Travel, Isolation, Spirituality",
    significance:
      "Foreign lands, spirituality, losses, hidden enemies, and final liberation. The dissolving of the material.",
  },
];

// ============ NAKSHATRAS (LUNAR MANSIONS) DATA ============
const NAKSHATRAS = [
  {
    number: 1,
    name: "Ashwini",
    ruler: "Ketu",
    range: "0° – 13°20' Aries",
    symbol: "Horse",
    traits: "Swift, healing, pioneering",
    deity: "Ashwins",
  },
  {
    number: 2,
    name: "Bharani",
    ruler: "Venus",
    range: "13°20' – 26°40' Aries",
    symbol: "Yoni",
    traits: "Procreative, nurturing, protective",
    deity: "Yama",
  },
  {
    number: 3,
    name: "Krittika",
    ruler: "Sun",
    range: "26°40' Aries – 10° Taurus",
    symbol: "Knife/Flame",
    traits: "Sharp, cutting, transformative",
    deity: "Agni",
  },
  {
    number: 4,
    name: "Rohini",
    ruler: "Moon",
    range: "10° – 23°20' Taurus",
    symbol: "Chariot",
    traits: "Gentle, nourishing, stable",
    deity: "Brahma",
  },
  {
    number: 5,
    name: "Mrigashira",
    ruler: "Mercury",
    range: "23°20' Taurus – 6°40' Gemini",
    symbol: "Deer Head",
    traits: "Seeking, curious, inquisitive",
    deity: "Soma",
  },
  {
    number: 6,
    name: "Ardra",
    ruler: "Rahu",
    range: "6°40' – 20° Gemini",
    symbol: "Teardrop",
    traits: "Intense, fierce, transformative",
    deity: "Rudra",
  },
  {
    number: 7,
    name: "Punarvasu",
    ruler: "Jupiter",
    range: "20° Gemini – 3°20' Cancer",
    symbol: "Bow & Arrow",
    traits: "Restoration, repetition, renewal",
    deity: "Aditi",
  },
  {
    number: 8,
    name: "Pushya",
    ruler: "Saturn",
    range: "3°20' – 16°40' Cancer",
    symbol: "Cow's Udder",
    traits: "Nourishing, supportive, auspicious",
    deity: "Brihaspati",
  },
  {
    number: 9,
    name: "Ashlesha",
    ruler: "Mercury",
    range: "16°40' – 30° Cancer",
    symbol: "Serpent Coil",
    traits: "Mysterious, intriguing, healing",
    deity: "Serpents",
  },
  {
    number: 10,
    name: "Magha",
    ruler: "Ketu",
    range: "0° – 13°20' Leo",
    symbol: "Royal Throne",
    traits: "Regal, authoritative, ancestral",
    deity: "Pitris (Ancestors)",
  },
  {
    number: 11,
    name: "Purva Phalguni",
    ruler: "Venus",
    range: "13°20' – 26°40' Leo",
    symbol: "Hammock/Bed",
    traits: "Luxurious, creative, fertile",
    deity: "Aryaman",
  },
  {
    number: 12,
    name: "Uttara Phalguni",
    ruler: "Sun",
    range: "26°40' Leo – 10° Virgo",
    symbol: "Bed/Couch",
    traits: "Generous, dutiful, service-oriented",
    deity: "Aryaman",
  },
  {
    number: 13,
    name: "Hasta",
    ruler: "Moon",
    range: "10° – 23°20' Virgo",
    symbol: "Hand",
    traits: "Skillful, dexterous, artistic",
    deity: "Savitar",
  },
  {
    number: 14,
    name: "Chitra",
    ruler: "Mercury",
    range: "23°20' Virgo – 6°40' Libra",
    symbol: "Jewel/Bright Star",
    traits: "Brilliant, creative, artful",
    deity: "Tvashtar",
  },
  {
    number: 15,
    name: "Swati",
    ruler: "Rahu",
    range: "6°40' – 20° Libra",
    symbol: "Sword",
    traits: "Adaptable, independent, windy",
    deity: "Vayu",
  },
  {
    number: 16,
    name: "Vishakha",
    ruler: "Jupiter",
    range: "20° Libra – 3°20' Scorpio",
    symbol: "Potter's Wheel",
    traits: "Dedicated, determined, zealous",
    deity: "Indra & Agni",
  },
  {
    number: 17,
    name: "Anuradha",
    ruler: "Saturn",
    range: "3°20' – 16°40' Scorpio",
    symbol: "Lotus",
    traits: "Devotional, disciplined, unifying",
    deity: "Mitra",
  },
  {
    number: 18,
    name: "Jyeshtha",
    ruler: "Mercury",
    range: "16°40' – 30° Scorpio",
    symbol: "Umbrella",
    traits: "Elder, dignified, protective",
    deity: "Indra",
  },
  {
    number: 19,
    name: "Mula",
    ruler: "Ketu",
    range: "0° – 13°20' Sagittarius",
    symbol: "Root",
    traits: "Investigative, destructive, transformative",
    deity: "Nirriti",
  },
  {
    number: 20,
    name: "Purva Ashadha",
    ruler: "Venus",
    range: "13°20' – 26°40' Sagittarius",
    symbol: "Elephant Tusk",
    traits: "Powerful, undefeated, joyful",
    deity: "Apas",
  },
  {
    number: 21,
    name: "Uttara Ashadha",
    ruler: "Sun",
    range: "26°40' Sagittarius – 10° Capricorn",
    symbol: "Elephant Tusk",
    traits: "Universal, exalted, steadfast",
    deity: "Vishnu",
  },
  {
    number: 22,
    name: "Shravana",
    ruler: "Moon",
    range: "10° – 23°20' Capricorn",
    symbol: "Ear",
    traits: "Listening, learning, devoted",
    deity: "Vishnu",
  },
  {
    number: 23,
    name: "Dhanishta",
    ruler: "Mercury",
    range: "23°20' Capricorn – 6°40' Aquarius",
    symbol: "Musical Drum",
    traits: "Rhythmic, wealthy, musical",
    deity: "Vasus",
  },
  {
    number: 24,
    name: "Shatabhisha",
    ruler: "Rahu",
    range: "6°40' – 20° Aquarius",
    symbol: "100 Stars",
    traits: "Healing, mysterious, adaptable",
    deity: "Varuna",
  },
  {
    number: 25,
    name: "Purva Bhadrapada",
    ruler: "Jupiter",
    range: "20° Aquarius – 3°20' Pisces",
    symbol: "Two Front Legs",
    traits: "Fierce, philanthropic, mysterious",
    deity: "Ajaikapada",
  },
  {
    number: 26,
    name: "Uttara Bhadrapada",
    ruler: "Saturn",
    range: "3°20' – 16°40' Pisces",
    symbol: "Two Back Legs",
    traits: "Humble, charitable, serene",
    deity: "Ahir Budhanya",
  },
  {
    number: 27,
    name: "Revati",
    ruler: "Mercury",
    range: "16°40' – 30° Pisces",
    symbol: "Fish or Drum",
    traits: "Compassionate, charitable, protecting",
    deity: "Pushan",
  },
];

// ============ PANCHANGA (FIVE LIMBS) DATA ============
const PANCHANGA = [
  {
    name: "Tithi",
    en: "Lunar Day",
    desc: "The lunar day based on the angle between Sun and Moon. 30 tithis in a lunar month.",
    count: "30 per lunar month",
  },
  {
    name: "Vara",
    en: "Weekday",
    desc: "The day of the week (7 days). Each ruled by one of the 7 classical planets.",
    count: "7 days",
  },
  {
    name: "Nakshatra",
    en: "Lunar Mansion",
    desc: "One of 27 lunar constellations the Moon passes through. Each spans 13°20'.",
    count: "27 stars",
  },
  {
    name: "Yoga",
    en: "Planetary Union",
    desc: "Formed by the combined longitude of Sun and Moon. Indicates the quality of the day.",
    count: "27 yogas",
  },
  {
    name: "Karana",
    en: "Half-Lunar Day",
    desc: "Half of a tithi. There are two karanas per tithi, totaling 60 in a lunar month.",
    count: "60 per lunar month",
  },
];

// ============ DASHA SYSTEM (120-YEAR CYCLE) ============
const VIMSHOTTARI_DASHA = [
  { planet: "Ketu", years: 7, color: "#6b4f3f" },
  { planet: "Venus", years: 20, color: "#c491d1" },
  { planet: "Sun", years: 6, color: "#e8a33a" },
  { planet: "Moon", years: 10, color: "#c8c8e8" },
  { planet: "Mars", years: 7, color: "#e85d3a" },
  { planet: "Rahu", years: 18, color: "#a55b1f" },
  { planet: "Jupiter", years: 16, color: "#d4a040" },
  { planet: "Saturn", years: 19, color: "#8b7355" },
  { planet: "Mercury", years: 17, color: "#6ac47a" },
];

// ============ TOOLS & TECHNIQUES DATA ============
const TOOLS = [
  {
    title: "Divisional Charts (Vargas)",
    desc: "The Rashi chart is divided into precise sections to examine specific life areas.",
    items: [
      "D1 (Rashi) – Overall personality and life",
      "D9 (Navamsha) – Marriage and spouse",
      "D10 (Dasamsha) – Career and profession",
      "D12 (Dwadasamsha) – Parents and lineage",
    ],
  },
  {
    title: "Planetary Strength (Sthana Bala)",
    desc: "Evaluates the positional and directional strength of planets in the chart.",
    items: [
      "Rashi Avastha – Planet's nature in its rashi",
      "Bhava Avastha – Planet's relationship to houses",
      "Dig Bala – Directional strength (cardinal points)",
      "Kala Bala – Temporal strength (seasonal, diurnal)",
    ],
  },
  {
    title: "Yogas (Planetary Combinations)",
    desc: "Specific planetary positions that create particular effects or destinies.",
    items: [
      "Raja Yoga – Combinations for power and success",
      "Dhana Yoga – Wealth-producing combinations",
      "Viparita Raja Yoga – Success through adversity",
      "Parivartana Yoga – Mutual exchange of planets",
    ],
  },
  {
    title: "Aspects (Drishti)",
    desc: "Planetary influence on other planets and houses through directional sight.",
    items: [
      "Full aspect (7th house) – Standard planetary view",
      "Mars aspects – 4th & 8th houses (aggressive influence)",
      "Jupiter/Saturn aspects – Specialized view patterns",
      "Rahu/Ketu aspects – Nodes' shadowy influence",
    ],
  },
];

// ============ BRANCHES OF JYOTISH ============
const BRANCHES = [
  {
    name: "Hora Shastra",
    en: "Electional Astrology",
    desc: "Determining auspicious times for beginning important activities.",
    icon: "fas fa-clock",
  },
  {
    name: "Siddhanta",
    en: "Mathematical Astronomy",
    desc: "Precise calculations of planetary positions and astronomical phenomena.",
    icon: "fas fa-calculator",
  },
  {
    name: "Samhita",
    en: "Mundane Astrology",
    desc: "Study of collective events: nations, weather, earthquakes, political upheavals.",
    icon: "fas fa-globe",
  },
  {
    name: "Prasna Shastra",
    en: "Horary Astrology",
    desc: "Answering specific questions through a chart cast at the moment of inquiry.",
    icon: "fas fa-question",
  },
  {
    name: "Nimitta Shastra",
    en: "Omens & Portents",
    desc: "Interpretation of signs, symbols, and natural phenomena as cosmic messages.",
    icon: "fas fa-eye",
  },
  {
    name: "Muhurta Shastra",
    en: "Auspicious Timing",
    desc: "Selecting optimal times for weddings, travel, business launches, and rituals.",
    icon: "fas fa-star",
  },
  {
    name: "Tajika Shastra",
    en: "Annual Progressions",
    desc: "Annual solar return charts and yearly predictive techniques.",
    icon: "fas fa-calendar",
  },
  {
    name: "Esoteric Jyotish",
    en: "Spiritual Astrology",
    desc: "Deeper understanding of soul purpose, karma, and spiritual evolution.",
    icon: "fas fa-om",
  },
];

// ============ EXPORT FOR SCRIPT.JS ============
// All data is now globally available
